// apps/site/src/app/page.tsx

export default function HomePage() {
  return (
    <main
      style={{
        minHeight: "100vh",
        display: "flex",
        alignItems: "center",
        justifyContent: "center",
        fontFamily: "system-ui, -apple-system, BlinkMacSystemFont, sans-serif"
      }}
    >
      <div style={{ textAlign: "center" }}>
        <h1 style={{ fontSize: "2rem", fontWeight: 700, marginBottom: "0.75rem" }}>
          lamman.site
        </h1>
        <p style={{ color: "#555" }}>
          Static landing pages generated by Lamman.
        </p>
      </div>
    </main>
  );
}
